spring.application.name=AssistantAi

# Dados de conexão com o banco H2
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
# H2 Client
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# JPA, SQL
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Configurações para o modelo de chat do Google AI Gemini
google-ai-gemini.chat-model.api-key=SUA_KEY_AQUI
google-ai-gemini.chat-model.model-name=gemini-2.5-flash


ollama-ai.chat-model.base.url=http://localhost:11434
ollama-ai.chat-model.model-name=gpt-oss:20b